FROM node:10-alpine
     
WORKDIR /home/client
 
# COPY package.json package.json
COPY . .
 
# RUN npm install
# RUN npm install mongodb --save
# COPY . .
 
# EXPOSE 3000
 
# RUN npm install -g nodemon
# RUN echo "bau "
CMD ["npm", "start"]