FROM node:10-alpine
     
WORKDIR /home/express-gateway
 
# COPY package.json package.json
COPY . .
 
# RUN npm install -g nodemon
 
# COPY . .
 
# EXPOSE 9876
 
# RUN npm install -g nodemon
# RUN npm start
CMD ["npm", "start"]
